# Print a new line at the start of the prompt
add_newline = true

# Make prompt a single line instead of two lines
[line_break]
disabled = false
 
# The "success_symbol" is set to "➜" with color "bold green"
[character]                         
success_symbol = "[➜](bold green)"
# The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"  
# The "success_symbol" is set to "➜" with color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[conda]
ignore_base = false
disabled = false
format = "[$symbol$environment](dimmed green) "
